/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DividendPayingTokenInterfaceInterface extends ethers.utils.Interface {
  functions: {
    "dividendOf(address)": FunctionFragment;
    "withdrawDividend()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "dividendOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "withdrawDividend",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "dividendOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawDividend",
    data: BytesLike
  ): Result;

  events: {
    "DividendWithdrawn(address,uint256)": EventFragment;
    "DividendsDistributed(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DividendWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DividendsDistributed"): EventFragment;
}

export class DividendPayingTokenInterface extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DividendPayingTokenInterfaceInterface;

  functions: {
    dividendOf(_owner: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "dividendOf(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdrawDividend(overrides?: Overrides): Promise<ContractTransaction>;

    "withdrawDividend()"(overrides?: Overrides): Promise<ContractTransaction>;
  };

  dividendOf(_owner: string, overrides?: CallOverrides): Promise<BigNumber>;

  "dividendOf(address)"(
    _owner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdrawDividend(overrides?: Overrides): Promise<ContractTransaction>;

  "withdrawDividend()"(overrides?: Overrides): Promise<ContractTransaction>;

  callStatic: {
    dividendOf(_owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "dividendOf(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawDividend(overrides?: CallOverrides): Promise<void>;

    "withdrawDividend()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    DividendWithdrawn(to: string | null, weiAmount: null): EventFilter;

    DividendsDistributed(from: string | null, weiAmount: null): EventFilter;
  };

  estimateGas: {
    dividendOf(_owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "dividendOf(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawDividend(overrides?: Overrides): Promise<BigNumber>;

    "withdrawDividend()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    dividendOf(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "dividendOf(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawDividend(overrides?: Overrides): Promise<PopulatedTransaction>;

    "withdrawDividend()"(overrides?: Overrides): Promise<PopulatedTransaction>;
  };
}
